development:
    api_key: YU6daOzB4FA7LAT1oaooDhfC3LuNSv1vEQVQ
    api_secret: RywCfMeV8ANmfFXmh4QTfNzSJESx7Cbdi1bi
    callback_path: http://app2.streamburst.net:3000/dvm/bebo_app

test:
    api_key: 
    api_secret: 
    callback_path: 

production:
    api_key: YU6daOzB4FA7LAT1oaooDhfC3LuNSv1vEQVQ
    api_secret: RywCfMeV8ANmfFXmh4QTfNzSJESx7Cbdi1bi
    callback_path: https://streamburst.tv/dvm/bebo_app
